version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    image: mywebapp:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
